######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 13 14:43:16 2014
######################################################################

TEMPLATE = app
TARGET = Lab2
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++0x -g 
QMAKE_CXXFLAGS_RELEASE -= -O2

# Input
HEADERS += parser.h
SOURCES += main.cpp parser.cpp

